-- Run this entire file in Supabase SQL Editor.
create table if not exists public.course_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null default 'turning-forward',
  progress jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, course_slug)
);

alter table public.course_progress enable row level security;

drop policy if exists "Students read own progress" on public.course_progress;
create policy "Students read own progress" on public.course_progress for select using (auth.uid() = user_id);

drop policy if exists "Students insert own progress" on public.course_progress;
create policy "Students insert own progress" on public.course_progress for insert with check (auth.uid() = user_id);

drop policy if exists "Students update own progress" on public.course_progress;
create policy "Students update own progress" on public.course_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists course_progress_user_id_idx on public.course_progress(user_id);

-- Stripe-backed course access. Run this section after the course_progress table.
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null,
  active boolean not null default true,
  stripe_checkout_session_id text unique,
  stripe_customer_id text,
  stripe_payment_intent_id text,
  purchased_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, course_slug)
);
alter table public.enrollments enable row level security;
drop policy if exists "Students read own enrollments" on public.enrollments;
create policy "Students read own enrollments" on public.enrollments for select using (auth.uid() = user_id);
create index if not exists enrollments_user_id_idx on public.enrollments(user_id);
