import assert from "node:assert/strict";
import fs from "node:fs";

const dashboard=fs.readFileSync(new URL("../app/dashboard/page.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../app/dashboard/dashboard.css",import.meta.url),"utf8");
assert.match(dashboard,/dashboard-shell/);
assert.match(dashboard,/dashboard-sidebar/);
assert.match(dashboard,/href="\/dashboard"/);
assert.match(dashboard,/href="\/course\/turning-forward"/);
assert.match(dashboard,/href="\/profile"/);
assert.doesNotMatch(dashboard,/Certificates|Achievements|Saved|Resources|Settings|Help/);
assert.match(dashboard,/Turning Forward: The Work Beyond Fear/);
assert.match(dashboard,/From Thought to Freedom/);
assert.match(dashboard,/DECEMBER 2026/i);
assert.match(dashboard,/course-thumbnails\/turning-forward\.png/);
assert.match(dashboard,/course-thumbnails\/from-thought-to-freedom\.png/);
assert.match(dashboard,/theme/);
assert.match(dashboard,/localStorage/);
assert.match(dashboard,/Light Mode|Dark Mode/);
assert.match(dashboard,/theme-toggle/);
assert.match(css,/\.dashboard-shell\.light/);
assert.match(css,/\.theme-toggle/);
console.log("dashboard theme and thumbnails contract passed");
