import assert from "node:assert/strict";
import fs from "node:fs";

const dashboard=fs.readFileSync(new URL("../app/dashboard/page.tsx",import.meta.url),"utf8");
assert.match(dashboard,/dashboard-shell/);
assert.match(dashboard,/dashboard-sidebar/);
assert.match(dashboard,/TCF LEARN/);
assert.match(dashboard,/href="\/dashboard"/);
assert.match(dashboard,/href="\/course\/turning-forward"/);
assert.match(dashboard,/href="\/profile"/);
assert.doesNotMatch(dashboard,/Certificates|Achievements|Saved|Resources|Settings|Help/);
assert.match(dashboard,/Turning Forward: The Work Beyond Fear/);
assert.match(dashboard,/From Thought to Freedom/);
assert.match(dashboard,/Correcting Criminal Thinking Errors/);
assert.match(dashboard,/COMING SOON/i);
assert.match(dashboard,/DECEMBER 2026/i);
assert.match(dashboard,/courseCatalog/);
assert.match(dashboard,/course-thumbnails\/turning-forward/);
assert.match(dashboard,/course-thumbnails\/from-thought-to-freedom/);
assert.match(dashboard,/ProgressBar/);
console.log("dashboard application shell contract passed");
