export type AnswerOption = { text: string; feedback: string };
export type QuizQuestion = { id: string; prompt: string; correct: string; options: AnswerOption[] };
export type ActivityField = { id: string; label: string; min?: number };
export type LessonContent = {
  number: number;
  title: string;
  videoTitle: string;
  intro: string;
  quote: string;
  sectionTitle: string;
  sectionBody: string;
  activityTitle: string;
  fields: ActivityField[];
  quiz: QuizQuestion[];
};
export type ChallengeContent = {
  title: string;
  description: string;
  fields: ActivityField[];
  pledge: string;
};
export type CourseModuleContent = {
  slug: string;
  number: number;
  title: string;
  description: string;
  lessons: LessonContent[];
  challenge: ChallengeContent;
};

const q=(id:string,prompt:string,correct:string,correctWhy:string,wrong:[string,string][]):QuizQuestion=>({
  id,prompt,correct,
  options:[
    {text:wrong[0][0],feedback:wrong[0][1]},
    {text:correct,feedback:correctWhy},
    {text:wrong[1][0],feedback:wrong[1][1]},
    {text:wrong[2][0],feedback:wrong[2][1]}
  ]
});

export const moduleContent: CourseModuleContent[] = [
{
slug:"module-2",number:2,title:"Fear Is a Signal, Not a Stop Sign",description:"Recognize fear, interrupt avoidance, and move deliberately while uncertainty is present.",
lessons:[
{number:1,title:"Name the Real Threat",videoTitle:"Why Your Brain Wants You to Stay Small",intro:"Fear becomes harder to manage when it stays vague. Naming the real threat separates what is actually happening from what your mind is predicting.",quote:"A named fear can be evaluated. An unnamed fear tends to run the room.",sectionTitle:"Separate danger from discomfort",sectionBody:"Ask what is objectively at risk, what is merely unfamiliar, and what evidence supports the story in your head. The goal is not to dismiss fear. The goal is to make fear specific enough to evaluate.",activityTitle:"Threat Check",fields:[{id:"fear",label:"The fear I am facing"},{id:"evidence",label:"Evidence that the threat is real"},{id:"discomfort",label:"What may simply be discomfort or uncertainty"},{id:"next",label:"One safe forward action I can take"}],quiz:[
q("q1","What is the first useful move when fear feels overwhelming?","Name the specific threat","Specific language turns a vague alarm into something you can evaluate.",[["Ignore the feeling","Ignoring fear removes useful information and often makes it return louder."],["Assume the worst","Worst-case assumptions are predictions, not evidence."],["Wait for fear to disappear","Fear often decreases after deliberate action, not before it."]]),
q("q2","Which question best tests whether fear is accurate?","What evidence supports this prediction?","Evidence helps distinguish a realistic risk from an automatic story.",[["How embarrassed will I feel?","Embarrassment may matter emotionally, but it does not establish whether the feared outcome is likely."],["Who can I blame if it goes wrong?","Blame does not help evaluate risk or improve the next decision."],["Can I avoid this forever?","Avoidance does not tell you whether the fear is accurate."]]),
q("q3","Discomfort is best understood as:","A possible sign of growth or unfamiliarity","Discomfort can accompany learning, change, and responsible risk without indicating actual danger.",[["Proof you should stop","Discomfort alone does not prove an action is unsafe."],["A guarantee of failure","Feeling uneasy does not predict the outcome."],["Something successful people never feel","Growth frequently includes discomfort for everyone."]]),
q("q4","A useful fear response combines:","Awareness, evaluation, and deliberate action","The lesson asks you to notice fear, assess it, then choose a measured next move.",[["Denial and speed","Rushing while denying fear can create poor decisions."],["Avoidance and reassurance","Temporary reassurance can reinforce avoidance instead of building confidence."],["Confidence before action","Waiting for complete confidence can keep you stuck."]])]},
{number:2,title:"The Avoidance Tax",videoTitle:"The Hidden Cost of Avoidance",intro:"Avoidance can feel like relief in the moment, but it often charges interest. Delayed conversations, applications, decisions, and responsibilities usually become heavier with time.",quote:"What you avoid today often becomes more expensive tomorrow.",sectionTitle:"Calculate the real cost",sectionBody:"Look beyond immediate comfort. Avoidance can cost time, money, trust, confidence, options, and momentum. When you calculate that tax, action often becomes less frightening than delay.",activityTitle:"Avoidance Audit",fields:[{id:"avoiding",label:"What I have been avoiding"},{id:"shortRelief",label:"What short-term relief avoidance gives me"},{id:"cost",label:"What this avoidance is costing me"},{id:"action",label:"One action that reduces the tax this week"}],quiz:[
q("q1","Why can avoidance feel attractive?","It provides short-term relief","Avoidance lowers discomfort temporarily, which can make the pattern feel rewarding.",[["It permanently solves the problem","The underlying issue usually remains and may grow."],["It always protects relationships","Unaddressed issues can damage trust and clarity."],["It increases confidence","Repeated avoidance commonly weakens confidence in your ability to act."]]),
q("q2","The avoidance tax can include:","Lost time, trust, money, and options","Avoidance can create costs across several areas of life, not just emotion.",[["Only stress","Stress is one cost, but the consequences can be broader."],["Only financial penalties","Money may be involved, but opportunity and relationship costs matter too."],["No real cost if nobody notices","Private avoidance can still reduce options, confidence, and progress."]]),
q("q3","What weakens an avoidance cycle?","Taking a small direct action","A manageable action teaches your nervous system that you can move while uncomfortable.",[["Thinking about the issue longer","Reflection without action can become another form of delay."],["Waiting for perfect timing","Perfect timing is often an avoidance story."],["Making the task larger","Increasing the size of the task usually increases resistance."]]),
q("q4","A good first anti-avoidance action should be:","Specific and small enough to complete","Small, concrete actions reduce ambiguity and build evidence of follow-through.",[["Dramatic and public","A large public move is not necessary and may add pressure."],["Dependent on someone else's approval","Your first move should focus on what you can control."],["Delayed until motivation is high","The point is to act without depending on motivation."]])]},
{number:3,title:"Build a Courage Ladder",videoTitle:"Building Your Courage Ladder",intro:"Courage grows through graduated practice. A courage ladder breaks one intimidating goal into steps that move from uncomfortable-but-manageable to genuinely challenging.",quote:"Courage is trained in reps, not announced in speeches.",sectionTitle:"Use progressive exposure",sectionBody:"Start with a step that stretches you without overwhelming you. Repeat it until it becomes more familiar, then move up. Each rung should be observable, specific, and within your control.",activityTitle:"Courage Ladder Builder",fields:[{id:"goal",label:"The fear-facing goal"},{id:"rung1",label:"Rung 1: easiest forward action"},{id:"rung2",label:"Rung 2: next level"},{id:"rung3",label:"Rung 3: meaningful stretch"},{id:"rung4",label:"Rung 4: full challenge"}],quiz:[
q("q1","What is the purpose of a courage ladder?","Break a fear-facing goal into progressive steps","Graduated steps make practice repeatable and prevent all-or-nothing thinking.",[["Eliminate fear before starting","The ladder is designed to help you act while fear is still present."],["Choose the hardest action first","Starting too high can overwhelm you and reinforce avoidance."],["Prove you are fearless","Courage is action with fear present, not the absence of fear."]]),
q("q2","A good first rung should be:","Uncomfortable but manageable","The first rung should create a stretch without flooding you.",[["Completely effortless","If there is no stretch, it may not build courage."],["The most terrifying step","Too much intensity can make practice unsustainable."],["Something another person must do","Your rung should focus on behavior you control."]]),
q("q3","When should you move to the next rung?","After practicing the current rung enough to build familiarity","Repetition creates evidence that you can tolerate and complete the action.",[["Only when you feel zero anxiety","Some anxiety may remain even when you are ready to progress."],["Immediately after writing the ladder","Planning alone does not build the tolerance that practice does."],["Whenever someone pressures you","The ladder should be deliberate, not driven by outside pressure."]]),
q("q4","Courage is best measured by:","Actions taken despite discomfort","Behavior provides stronger evidence of courage than how confident you felt beforehand.",[["How calm you felt","Calmness is not required for courageous action."],["How impressive the action looked","Courage is personal and does not need an audience."],["How quickly fear disappeared","Fear reduction may follow, but it is not the primary measure."]])]}],
challenge:{title:"Practice Courage in Sequence",description:"Complete the first two rungs of your courage ladder this week and record what happened before, during, and after each action.",fields:[{id:"commit1",label:"First rung I will complete"},{id:"commit2",label:"Second rung I will complete"},{id:"evidence",label:"What evidence will show I followed through"}],pledge:"I commit to practicing courage through action, not waiting for fear to disappear."}
},
{
slug:"module-3",number:3,title:"Systems Beat Motivation",description:"Replace emotional momentum with repeatable routines and disciplined systems.",lessons:[
{number:1,title:"Motivation Is a Visitor",videoTitle:"Motivation Is a Terrible Boss",intro:"Motivation rises and falls with mood, energy, stress, sleep, and circumstances. A life built only on motivation becomes unpredictable.",quote:"Use motivation when it shows up. Never make it responsible for your future.",sectionTitle:"Build for low-motivation days",sectionBody:"A system decides in advance what happens when you do not feel inspired. The question is not whether you feel ready. It is what the minimum action is when readiness is absent.",activityTitle:"Motivation Reality Check",fields:[{id:"goal",label:"A goal I keep relying on motivation to complete"},{id:"pattern",label:"What usually happens when motivation drops"},{id:"system",label:"A system that can replace the decision"}],quiz:[
q("q1","Why is motivation unreliable as a primary strategy?","It changes with mood and circumstances","Because motivation fluctuates, depending on it makes execution inconsistent.",[["It is always harmful","Motivation can help; it simply should not be the only system."],["It makes goals too specific","Specific goals are useful and unrelated to motivation's reliability."],["It only works for athletes","Motivation affects behavior in every area of life."]]),
q("q2","A system is valuable because it:","Pre-decides repeatable behavior","Systems reduce the number of daily decisions required to follow through.",[["Guarantees perfect results","Systems improve consistency but do not guarantee outcomes."],["Removes all effort","Execution still requires effort."],["Makes goals unnecessary","Systems work best when connected to meaningful goals."]]),
q("q3","The best plan for a low-energy day is:","A defined minimum action","A minimum standard protects consistency when your capacity is lower.",[["Skip everything","Skipping automatically breaks the practice loop."],["Double the workload tomorrow","Debt-based plans can create more avoidance."],["Wait for inspiration","Waiting keeps motivation in charge."]]),
q("q4","Consistency is strengthened when:","The next action is obvious","Clear cues and actions reduce friction and decision fatigue.",[["Every day requires a new plan","Constant redesign creates unnecessary decisions."],["Goals remain vague","Vague goals make execution harder."],["You depend on pressure","Pressure can produce short bursts but is not a stable system."]])]},
{number:2,title:"Design Your Minimum Standard",videoTitle:"Build a Life That Doesn’t Require Willpower",intro:"A minimum standard is the smallest version of a behavior that still keeps your promise to yourself. It protects identity and continuity on difficult days.",quote:"When you cannot do the maximum, protect the minimum.",sectionTitle:"Make success repeatable",sectionBody:"Your minimum should be measurable, realistic, and meaningful. Ten minutes of focused work may be better than an ambitious two-hour plan you repeatedly avoid.",activityTitle:"Minimum Standard Builder",fields:[{id:"area",label:"Area I need consistency in"},{id:"ideal",label:"My ideal action"},{id:"minimum",label:"My minimum standard"},{id:"cue",label:"When and where I will do it"}],quiz:[
q("q1","A minimum standard is:","The smallest meaningful version of the behavior","It keeps the habit alive while respecting real changes in capacity.",[["The least effort you can get away with","The purpose is integrity and continuity, not avoidance."],["A temporary excuse to quit","A minimum standard is designed to preserve follow-through."],["The same as your ideal target","The minimum is intentionally smaller than the ideal."]]),
q("q2","Why make the minimum measurable?","So completion is clear","A measurable standard removes ambiguity about whether you followed through.",[["So it looks impressive","The standard exists for execution, not appearance."],["To compete with other people","The standard should fit your life, not someone else's."],["To make it harder","Measurement should clarify, not inflate, the task."]]),
q("q3","Which is the strongest minimum standard?","Read 10 pages before bed","It states a concrete behavior and quantity.",[["Read more","This is too vague to measure reliably."],["Become a reader","That is an identity goal, not a specific action."],["Read whenever I feel like it","The cue depends on mood and provides no schedule."]]),
q("q4","Minimum standards protect:","Consistency and identity","Following through on a smaller promise still reinforces the identity of a person who keeps commitments.",[["Perfection","The minimum exists specifically because perfection is unrealistic."],["Other people's expectations","It is designed around your commitments and capacity."],["Constant intensity","Sustainable consistency matters more than maximum intensity."]])]},
{number:3,title:"Build Your Weekly Operating System",videoTitle:"The Compound Effect of Small Decisions",intro:"A weekly operating system gives your priorities a recurring home. It turns important intentions into calendar commitments, reviews, and repeatable rhythms.",quote:"What gets a place on the calendar has a better chance of becoming a life.",sectionTitle:"Run the week on purpose",sectionBody:"Choose recurring blocks for work, growth, relationships, health, money, and recovery. Add a weekly review so the system can improve rather than silently fail.",activityTitle:"Weekly Operating System",fields:[{id:"priorities",label:"My three weekly priorities"},{id:"blocks",label:"Recurring blocks I will schedule"},{id:"review",label:"Day and time for my weekly review"},{id:"adjust",label:"One rule for adjusting when life changes"}],quiz:[
q("q1","The main purpose of a weekly operating system is to:","Give priorities recurring time and structure","Scheduling recurring blocks makes execution more predictable.",[["Fill every minute","A useful system leaves room for rest and change."],["Remove flexibility","Good systems include adjustment rules."],["Replace all goals","The system is how goals receive consistent action."]]),
q("q2","Why include a weekly review?","To learn and adjust the system","A review turns missed targets into information for improvement.",[["To punish yourself for misses","Shame reduces learning and does not improve the design."],["To add more goals every week","More goals are not automatically better."],["To compare your week to others","The review should measure your own priorities and evidence."]]),
q("q3","A calendar block is strongest when it includes:","A specific time and activity","Clear time and behavior make the commitment executable.",[["A general intention","Vague intentions are easier to displace."],["Only a motivational quote","Inspiration does not reserve time."],["Several unrelated tasks","Overloaded blocks reduce clarity."]]),
q("q4","If the system repeatedly fails, you should:","Adjust the design using evidence","A system is a tool; recurring failure is feedback that the design needs work.",[["Assume you lack character","Personal shame hides design problems."],["Keep it unchanged forever","A rigid system can become unrealistic."],["Abandon structure entirely","Failure of one design does not mean systems are useless."]])]}],
challenge:{title:"Run the System for Seven Days",description:"Follow your weekly operating system for seven days. Track completion without judging yourself, then use the evidence to make one adjustment.",fields:[{id:"system",label:"The system I am committing to"},{id:"track",label:"How I will track completion"},{id:"review",label:"When I will review the evidence"}],pledge:"I commit to measuring consistency instead of relying on motivation."}
},
{
slug:"module-4",number:4,title:"Relationships and Boundaries",description:"Rebuild trust, protect your progress, and define healthy access to your life.",lessons:[
{number:1,title:"Not Everyone Can Follow You Forward",videoTitle:"Not Everyone Can Go Where You’re Going",intro:"Growth changes access. Some relationships can adapt to your new standards; others may depend on the version of you that you are trying to leave behind.",quote:"History with someone does not automatically guarantee access to your future.",sectionTitle:"Evaluate alignment, not just history",sectionBody:"Ask whether a relationship supports honesty, accountability, safety, and growth. Compassion does not require unlimited access.",activityTitle:"Relationship Alignment Check",fields:[{id:"relationship",label:"Relationship I need to evaluate"},{id:"supports",label:"Ways this relationship supports growth"},{id:"pulls",label:"Ways it pulls me backward"},{id:"decision",label:"Access level I need going forward"}],quiz:[
q("q1","Healthy relationship decisions should be based primarily on:","Current alignment and behavior","Present patterns are more useful than history alone when deciding access.",[["How long you have known someone","Time alone does not guarantee health or alignment."],["Guilt","Guilt can pressure you into access that violates your values."],["What outsiders expect","Boundaries should reflect your needs, safety, and values."]]),
q("q2","Compassion requires:","Care without necessarily granting unlimited access","You can care about someone and still limit access to protect growth and safety.",[["Saying yes to everything","Unlimited yeses can become self-abandonment."],["Ignoring harmful patterns","Compassion does not require denial."],["Keeping every relationship unchanged","Growth may require different boundaries."]]),
q("q3","A relationship may be misaligned if it repeatedly:","Rewards old destructive patterns","A relationship that depends on your old behavior can undermine forward identity.",[["Challenges you respectfully","Respectful challenge can support growth."],["Respects your boundaries","Respect is a sign of health."],["Encourages accountability","Accountability can strengthen transformation."]]),
q("q4","Choosing distance can be:","A responsible boundary","Distance can be appropriate when access repeatedly harms stability or growth.",[["Always an act of revenge","A boundary can be protective rather than punitive."],["Proof you do not care","Care and distance can coexist."],["A failure to communicate","Sometimes distance follows clear communication and repeated violations."]])]},
{number:2,title:"Stop Over-Explaining",videoTitle:"Boundaries Are Not Rejection",intro:"Over-explaining often comes from fear that your boundary will not be accepted unless everyone agrees with your reasoning. A boundary does not require a courtroom argument.",quote:"Clarity is enough. Agreement is optional.",sectionTitle:"Communicate without negotiating your values",sectionBody:"State the boundary, the reason if useful, and the action you will take if it is crossed. Avoid turning your limit into a debate.",activityTitle:"Boundary Script Builder",fields:[{id:"boundary",label:"The boundary I need to communicate"},{id:"reason",label:"My concise reason"},{id:"consequence",label:"What I will do if the boundary is crossed"}],quiz:[
q("q1","A boundary is primarily about:","What you will do to protect a limit","Boundaries define your behavior and access, not control over another person.",[["Forcing others to agree","Agreement cannot be controlled."],["Punishing someone","Consequences protect limits; punishment seeks retaliation."],["Winning an argument","A boundary is not a debate prize."]]),
q("q2","Over-explaining often signals:","A need for permission or agreement","Long justifications can become attempts to make the other person approve the boundary.",[["Strong confidence","Confidence usually allows concise clarity."],["Better communication in every case","More words can create more openings for negotiation."],["That the boundary is wrong","A valid boundary can still trigger anxiety."]]),
q("q3","A concise boundary should include:","The limit and what you will do if needed","This keeps the message actionable and within your control.",[["Every detail of your history","Excess detail is usually unnecessary."],["A threat you cannot enforce","Unrealistic threats weaken credibility."],["An apology for having needs","You can be respectful without apologizing for a reasonable limit."]]),
q("q4","If someone dislikes your boundary, that means:","They dislike the boundary; it does not automatically make it wrong","Discomfort from others is information, not proof that your limit is unhealthy.",[["You must remove it","A boundary should not depend on immediate approval."],["You communicated badly","Even clear communication can be disliked."],["You are rejecting them as a person","Limits address access or behavior, not human worth."]])]},
{number:3,title:"Trust Is Built in Layers",videoTitle:"Trust Is Earned in Layers",intro:"Trust should not be all-or-nothing. Healthy rebuilding happens through small promises, observed behavior, and increased access over time.",quote:"Trust is not restored by one conversation. It is built through repeated evidence.",sectionTitle:"Let access follow evidence",sectionBody:"Separate forgiveness, reconciliation, and trust. You can release resentment without restoring the same level of access. Let consistency determine the next layer.",activityTitle:"Trust Ladder",fields:[{id:"person",label:"Relationship where trust is being rebuilt"},{id:"evidence",label:"Evidence I need to see"},{id:"small",label:"A small level of access I can test"},{id:"next",label:"What would justify the next layer"}],quiz:[
q("q1","Trust is best rebuilt through:","Repeated evidence over time","Consistent behavior gives stronger proof than promises alone.",[["One emotional conversation","A meaningful conversation can start repair but cannot prove long-term consistency."],["Immediate full access","Full access before evidence can ignore unresolved risk."],["Pretending nothing happened","Denial prevents genuine repair."]]),
q("q2","Forgiveness and trust are:","Related but not identical","You can forgive while still requiring evidence before restoring access.",[["Exactly the same","Forgiveness can be internal while trust depends on behavior."],["Always simultaneous","They may happen on different timelines."],["Both owed immediately","Trust is earned through evidence."]]),
q("q3","Layered trust means:","Access increases as evidence increases","Small tests let trust grow without requiring an all-or-nothing leap.",[["Never trusting anyone again","Layering allows cautious rebuilding rather than permanent shutdown."],["Testing people secretly","Healthy rebuilding should be based on observable agreements and behavior."],["Ignoring past patterns","Past patterns inform what evidence is needed."]]),
q("q4","A broken promise during rebuilding should be treated as:","New information to evaluate","The response should consider the pattern, impact, accountability, and repair.",[["Proof nobody can change","One event does not justify a universal conclusion."],["Something to ignore","Ignoring breaches weakens boundaries and learning."],["A reason for automatic revenge","Revenge does not restore trust or clarity."]])]}],challenge:{title:"Communicate One Overdue Boundary",description:"Choose one boundary you have delayed, communicate it clearly, and calmly follow through if it is tested.",fields:[{id:"boundary",label:"Boundary I will communicate"},{id:"words",label:"The exact words I will use"},{id:"follow",label:"How I will follow through if tested"}],pledge:"I commit to communicating my boundary clearly and following through without unnecessary argument."}
},
{
slug:"module-5",number:5,title:"Financial Rebuild Strategy",description:"Develop stability, face the numbers, and create a practical rebuild sequence.",lessons:[
{number:1,title:"Face the Numbers",videoTitle:"Stop Hiding From Your Money",intro:"Financial clarity begins with accurate numbers, not guesses. Avoiding statements, balances, bills, or spending creates anxiety without creating a plan.",quote:"Numbers are information. They become strategy when you face them.",sectionTitle:"Replace financial fog with facts",sectionBody:"List income, fixed expenses, variable spending, debts, savings, and overdue obligations. The first win is not a perfect budget. It is knowing what is true.",activityTitle:"Financial Snapshot",fields:[{id:"income",label:"Monthly take-home income"},{id:"fixed",label:"Monthly fixed expenses"},{id:"debt",label:"Current debts and minimum payments"},{id:"gap",label:"The biggest gap or pressure point I see"}],quiz:[
q("q1","The first step in financial rebuilding is:","Get accurate numbers","A plan must be based on what is actually coming in, going out, and owed.",[["Buy better budgeting software","Tools cannot replace accurate information."],["Increase your lifestyle","More spending before clarity can increase instability."],["Wait until income improves","Clarity is useful at any income level."]]),
q("q2","Avoiding financial information usually:","Increases uncertainty and delays decisions","Avoidance may reduce discomfort briefly but leaves the underlying numbers unchanged.",[["Protects your credit","Not looking at balances does not protect credit."],["Makes debt smaller","Debt does not shrink because it is ignored."],["Creates a better plan automatically","Planning requires facts."]]),
q("q3","A financial snapshot should include:","Income, expenses, debts, and savings","These categories show your current position and available options.",[["Only income","Income alone does not show obligations or spending."],["Only debt","Debt alone misses cash flow and assets."],["Only future goals","Goals matter, but current facts come first."]]),
q("q4","Financial clarity is useful because it:","Turns anxiety into specific decisions","Once numbers are visible, you can prioritize actions instead of reacting to uncertainty.",[["Guarantees wealth","Clarity supports better choices but cannot guarantee outcomes."],["Removes every financial problem","The problems may remain, but they become more actionable."],["Makes budgeting unnecessary","Clarity is the foundation of budgeting."]])]},
{number:2,title:"Stability Before Appearance",videoTitle:"Stability Before Status",intro:"Rebuilding often requires choosing boring stability over visible status. The goal is margin, reliability, and reduced fragility before lifestyle expansion.",quote:"Looking stable and being stable are two different financial conditions.",sectionTitle:"Protect the base first",sectionBody:"Prioritize essentials, emergency margin, required payments, and income stability before image-driven spending. The sequence matters because fragile finances magnify every unexpected event.",activityTitle:"Stability Filter",fields:[{id:"essential",label:"My essential monthly needs"},{id:"appearance",label:"One appearance/status expense I can reduce"},{id:"buffer",label:"My first emergency-buffer target"},{id:"redirect",label:"Where I will redirect the freed money"}],quiz:[
q("q1","Stability before status means:","Build financial margin before lifestyle expansion","Margin reduces fragility and gives future choices more room.",[["Never enjoy money","The lesson is about sequence, not permanent deprivation."],["Hide all financial progress","Visibility is irrelevant; the point is actual stability."],["Avoid every purchase","Spending should be aligned with priorities, not eliminated entirely."]]),
q("q2","An emergency buffer helps by:","Reducing the impact of unexpected costs","Cash reserves can keep one surprise from becoming new debt or missed essentials.",[["Guaranteeing no emergencies happen","A buffer prepares for emergencies; it cannot prevent them."],["Replacing insurance in every case","Insurance and savings serve different purposes."],["Making income unnecessary","A buffer is not a permanent income source."]]),
q("q3","Image-driven spending is risky during rebuilding because it:","Uses resources needed for stability","Status purchases can compete with debt, reserves, and essential obligations.",[["Is always morally wrong","The issue is timing and priorities, not moral worth."],["Automatically ruins credit","Not every purchase affects credit directly."],["Means you can never recover","One choice does not define the whole rebuild."]]),
q("q4","A strong rebuild decision asks:","Does this strengthen or weaken my financial base?","This filter keeps the sequence focused on stability.",[["Will people be impressed?","External approval is a weak financial metric."],["Can I buy it today?","Affordability today does not show long-term impact."],["Is everyone else buying it?","Other people's spending is not your plan."]])]},
{number:3,title:"Create a Rebuild Sequence",videoTitle:"Building a Financial Recovery Plan",intro:"A rebuild sequence prevents everything from feeling equally urgent. You decide what gets handled first, second, and third based on risk, stability, and leverage.",quote:"Progress accelerates when every dollar has a next job.",sectionTitle:"Prioritize in order",sectionBody:"A practical sequence may begin with essentials and overdue risks, then a starter buffer, high-cost debt, income growth, and longer-term goals. Your exact order should reflect your situation.",activityTitle:"My Rebuild Sequence",fields:[{id:"first",label:"My first financial priority"},{id:"second",label:"My second priority"},{id:"third",label:"My third priority"},{id:"income",label:"One income-growth action I will take"}],quiz:[
q("q1","Why use a rebuild sequence?","To focus resources in a deliberate order","Priorities keep limited money and attention from being scattered.",[["To solve every problem at once","Trying to attack everything equally can dilute progress."],["To avoid reviewing the plan","Sequences should be reviewed as conditions change."],["To copy someone else's finances","Your order should match your risks and obligations."]]),
q("q2","High-risk overdue essentials should generally be:","Addressed early","Housing, utilities, transportation, or other critical risks can destabilize the entire rebuild.",[["Ignored until debt is gone","Critical obligations may require earlier attention."],["Hidden from the budget","Unlisted obligations create false clarity."],["Paid only if money is left over","Essentials usually need deliberate priority."]]),
q("q3","Income growth belongs in a rebuild because:","A stronger cash flow can expand options","Expense control matters, but increased income can improve the speed and resilience of recovery.",[["Budgets never work","Budgeting and income growth can work together."],["Spending does not matter","Cash flow has both income and spending sides."],["It guarantees quick wealth","Income growth improves capacity but is not a guarantee."]]),
q("q4","A rebuild plan should be:","Specific, prioritized, and revisited","Financial conditions change, so the sequence should be clear but adjustable.",[["Permanent and unchangeable","Rigid plans can become outdated."],["Based on shame","Shame does not improve financial math."],["Kept entirely in your head","Written priorities are easier to track and review."]])]}],challenge:{title:"Track Every Dollar for Seven Days",description:"Track every dollar for seven days and complete one concrete action from your rebuild sequence.",fields:[{id:"tracker",label:"How I will track every dollar"},{id:"action",label:"The rebuild action I will complete"},{id:"result",label:"What result I expect from that action"}],pledge:"I commit to using accurate numbers and deliberate priorities instead of financial avoidance."}
},
{
slug:"module-6",number:6,title:"Purpose Beyond the Pain",description:"Turn lived experience into wisdom, service, value, and a clear personal mission.",lessons:[
{number:1,title:"Pain Is Material, Not the Mission",videoTitle:"Your Pain Is Not Your Personality",intro:"Pain can shape you without becoming the only way you understand yourself. Your story is material you can learn from, not a permanent job description.",quote:"What happened to you can inform your purpose without becoming your entire identity.",sectionTitle:"Extract lessons without worshiping the wound",sectionBody:"Identify skills, values, insights, and empathy developed through experience. The goal is not to stay attached to pain in order to remain meaningful.",activityTitle:"Experience to Wisdom",fields:[{id:"experience",label:"An experience that shaped me"},{id:"lesson",label:"What it taught me"},{id:"strength",label:"Strength or skill I developed"},{id:"beyond",label:"Who I am beyond that experience"}],quiz:[
q("q1","Pain is described in this lesson as:","Material that can produce learning","Experience can become insight without becoming your permanent identity.",[["Your permanent identity","Reducing yourself to pain limits growth."],["Something that must be forgotten","Integration is different from erasure."],["The only source of purpose","Purpose can also come from strengths, values, and service."]]),
q("q2","Healthy meaning-making asks:","What did I learn and how can I use it?","This moves from experience toward wisdom and usefulness.",[["How do I keep reliving it?","Repeated reliving is not the same as extracting wisdom."],["How can I make everyone feel sorry for me?","Purpose is not built on permanent sympathy."],["How do I prove my pain was worse?","Comparison does not create meaning."]]),
q("q3","Moving beyond a painful identity means:","Expanding your identity, not denying your history","You can honor what happened while recognizing additional strengths and roles.",[["Pretending it had no effect","Denial blocks integration."],["Never discussing it again","You may choose to discuss it when useful and appropriate."],["Forgiving everyone immediately","Identity growth does not require a prescribed forgiveness timeline."]]),
q("q4","Wisdom becomes useful when it:","Changes choices or helps someone","Applied insight turns experience into practical value.",[["Stays completely abstract","Unused insight has limited practical impact."],["Makes you superior to others","Wisdom should not become ego."],["Requires constant suffering","Growth does not require remaining in pain."]])]},
{number:2,title:"Purpose Requires Usefulness",videoTitle:"Finding the People You’re Meant to Serve",intro:"Purpose becomes clearer when you stop asking only what you are meant to feel and start asking where your strengths can be useful.",quote:"Purpose grows where your strengths meet a real need.",sectionTitle:"Look for the intersection",sectionBody:"Identify people, problems, or environments where your experience and abilities create value. Purpose is not only a title; it can be a pattern of useful contribution.",activityTitle:"Usefulness Map",fields:[{id:"strengths",label:"Strengths I can offer"},{id:"people",label:"People or communities I understand"},{id:"problems",label:"Problems I can help solve"},{id:"service",label:"One useful contribution I can make now"}],quiz:[
q("q1","Purpose becomes practical when it connects:","Strengths to real needs","The intersection of capability and need creates useful contribution.",[["Status to attention","Visibility is not the same as usefulness."],["Pain to constant retelling","Storytelling can help, but purpose requires value beyond repetition."],["Ambition to comparison","Comparison does not define service."]]),
q("q2","Usefulness is broader than a job title because:","Contribution can happen in many roles","Purpose may appear in work, family, community, mentorship, creativity, or service.",[["Jobs never matter","Work can be one meaningful channel of contribution."],["Titles are always fake","Titles can describe real responsibility; they simply are not the whole purpose."],["Purpose requires volunteering","Paid and unpaid contribution can both be purposeful."]]),
q("q3","A good purpose experiment is:","A small act of service using a real strength","Experiments create evidence about what feels useful and sustainable.",[["Announce a huge mission first","A large announcement provides less evidence than action."],["Wait for perfect certainty","Purpose often becomes clearer through practice."],["Copy someone else's calling","Their fit may not match your strengths or community."]]),
q("q4","A useful contribution should ideally be:","Helpful and sustainable","Service that consistently destroys your capacity is hard to sustain.",[["Exhausting to prove commitment","Burnout is not proof of purpose."],["Invisible to the recipient","Usefulness should respond to a real need."],["Dependent on praise","Purpose becomes fragile when it requires applause."]])]},
{number:3,title:"Serve Without Self-Abandonment",videoTitle:"Building a Legacy Instead of a Story",intro:"Service without boundaries can become another form of self-neglect. Sustainable purpose includes limits, rest, and responsibility to your own life.",quote:"You do not have to destroy yourself to prove you care.",sectionTitle:"Build sustainable service",sectionBody:"Define what you can give, what you cannot give, and how you will recover. Your service should be aligned with your values without recreating chaos in your own life.",activityTitle:"Sustainable Service Plan",fields:[{id:"serve",label:"Who or what I want to serve"},{id:"give",label:"What I can realistically give"},{id:"limit",label:"A boundary that protects sustainability"},{id:"recover",label:"How I will restore my capacity"}],quiz:[
q("q1","Self-abandonment in service looks like:","Ignoring your own limits until you become unstable","Service becomes unsustainable when your own responsibilities and capacity are repeatedly sacrificed.",[["Having reasonable boundaries","Boundaries can preserve long-term service."],["Taking scheduled rest","Recovery supports sustainability."],["Saying no to work outside your capacity","A responsible no can protect the quality of your yes."]]),
q("q2","Sustainable service requires:","Boundaries and recovery","Limits and restoration help prevent burnout and resentment.",[["Constant availability","Always-on access can exhaust capacity."],["No personal priorities","Your life responsibilities still matter."],["Never changing your role","Service may need to evolve as circumstances change."]]),
q("q3","A healthy boundary in service is:","A clear limit that protects capacity","Limits help contribution remain deliberate and repeatable.",[["Refusing all requests","A boundary is selective, not necessarily total withdrawal."],["Helping only when praised","Praise is not a reliable boundary."],["Taking responsibility for everyone","You cannot control or carry every outcome."]]),
q("q4","Legacy is strengthened by:","Consistent useful action over time","Repeated contribution builds more durable impact than a single story or performance.",[["One dramatic moment","One moment can matter but does not replace consistency."],["Being known by everyone","Reach and legacy are not identical."],["Never making mistakes","Learning and repair are part of long-term contribution."]])]}],challenge:{title:"Complete One Purposeful Act of Service",description:"Use one of your strengths to complete a purposeful act of service while respecting a clear boundary.",fields:[{id:"act",label:"The act of service I will complete"},{id:"strength",label:"The strength I will use"},{id:"boundary",label:"The boundary that will keep it sustainable"}],pledge:"I commit to serving from strength and responsibility, not self-abandonment."}
},
{
slug:"module-7",number:7,title:"Leadership After Loss",description:"Lead with integrity, accountability, service, and influence that does not depend on ego.",lessons:[
{number:1,title:"Survival Is Not the Same as Leadership",videoTitle:"From Survivor to Leader",intro:"Survival skills can keep you alive in hard environments, but leadership requires a different operating system: foresight, responsibility, emotional regulation, and service.",quote:"What kept you alive may not be what helps you lead.",sectionTitle:"Shift from reaction to stewardship",sectionBody:"Leadership asks what your choices create for other people, not only whether you can survive the moment. It requires considering impact, standards, and the example you are setting.",activityTitle:"Survival-to-Leadership Shift",fields:[{id:"survival",label:"A survival behavior I still use"},{id:"impact",label:"How it affects others now"},{id:"leadership",label:"The leadership behavior that should replace it"},{id:"practice",label:"Where I will practice the new behavior"}],quiz:[
q("q1","Leadership differs from survival because leadership emphasizes:","Impact, responsibility, and stewardship","Leadership considers what your behavior creates for others and the future.",[["Winning every conflict","Winning is not the same as leading."],["Protecting yourself at all costs","Leadership often balances self-protection with responsibility to others."],["Never showing vulnerability","Appropriate vulnerability can strengthen trust."]]),
q("q2","A survival behavior can become a problem when:","It remains active in environments where it no longer fits","A strategy that once protected you may create conflict or mistrust in a different context.",[["It helped you in the past","Past usefulness alone does not make a behavior harmful."],["You remember why you learned it","Understanding the origin can support change."],["You replace it deliberately","Replacement is part of growth."]]),
q("q3","Stewardship means:","Taking responsibility for what has been entrusted to you","Leadership includes care for people, resources, influence, and consequences.",[["Controlling everyone","Control is not the same as stewardship."],["Avoiding hard decisions","Stewardship often requires difficult choices."],["Keeping all authority for yourself","Good leadership can share responsibility."]]),
q("q4","A leader should evaluate behavior by asking:","What does this choice create for the people and future I am responsible for?","This question shifts attention from immediate reaction to longer-term impact.",[["How do I look strongest?","Image can distract from actual impact."],["How do I avoid all criticism?","Leadership cannot eliminate criticism."],["How do I make everyone agree?","Agreement is not fully controllable."]])]},
{number:2,title:"Accountability Without Shame",videoTitle:"Accountability Without Shame",intro:"Accountability is the ability to face impact, own your part, repair what you can, and adjust behavior. Shame turns accountability into identity destruction.",quote:"Accountability says I did it. Shame says that is all I am.",sectionTitle:"Own, repair, adjust",sectionBody:"Strong leaders can admit mistakes without collapsing or becoming defensive. The goal is to protect truth and learning, not ego.",activityTitle:"Accountability Review",fields:[{id:"event",label:"A mistake or decision I need to own"},{id:"impact",label:"The impact it had"},{id:"repair",label:"What repair is possible"},{id:"change",label:"What I will change going forward"}],quiz:[
q("q1","Accountability includes:","Ownership, repair, and changed behavior","Accountability is more than admitting facts; it also includes response and adjustment.",[["Self-hatred","Shame can interfere with useful repair."],["Excuses that remove your part","Context matters, but accountability still names what was yours."],["Public humiliation","Humiliation is not required for responsibility."]]),
q("q2","Shame is risky because it can:","Turn a behavior into a permanent identity judgment","When the self is condemned, learning and repair become harder.",[["Guarantee better behavior","Harsh self-judgment does not reliably produce change."],["Make facts clearer","Shame can distort facts through defensiveness or collapse."],["Replace the need for repair","Feeling bad is not the same as repairing impact."]]),
q("q3","A strong leadership apology should:","Name the impact and the change you will make","Specific ownership and changed behavior make an apology more credible.",[["Focus mainly on your intentions","Intent can matter, but impact still needs acknowledgment."],["Demand immediate forgiveness","Forgiveness is not owed on your timeline."],["Include excuses before ownership","Excuses can weaken accountability."]]),
q("q4","Defensiveness interferes with accountability because it:","Protects ego instead of examining impact","Leadership requires enough stability to hear information that may be uncomfortable.",[["Always proves innocence","Defensiveness is a reaction, not evidence."],["Automatically repairs trust","Repair requires ownership and action."],["Makes feedback more accurate","Defensiveness can actually reduce accurate listening."]])]},
{number:3,title:"Create Your Leadership Code",videoTitle:"Living Your Leadership Code",intro:"A leadership code is a small set of standards you can use when pressure makes decisions harder. It defines who you intend to be before the moment arrives.",quote:"Values become leadership when they are translated into behavior.",sectionTitle:"Turn values into operating rules",sectionBody:"Choose standards that are specific enough to guide decisions: tell the truth early, address conflict directly, do not promise what you cannot deliver, protect dignity, and repair quickly.",activityTitle:"Leadership Code Builder",fields:[{id:"value1",label:"Leadership standard 1"},{id:"value2",label:"Leadership standard 2"},{id:"value3",label:"Leadership standard 3"},{id:"pressure",label:"How I will use the code under pressure"}],quiz:[
q("q1","A leadership code is useful because it:","Pre-decides standards before pressure hits","Predefined principles reduce impulsive decision-making in difficult moments.",[["Eliminates all difficult choices","Standards guide choices but do not remove complexity."],["Guarantees everyone likes you","Integrity can still create disagreement."],["Replaces judgment entirely","Principles still require context and judgment."]]),
q("q2","A strong leadership standard should be:","Behavioral and specific","Specific rules are easier to apply than abstract values alone.",[["Vague and inspirational only","Inspiration without behavior is hard to execute."],["Designed to impress others","The code should guide conduct, not image."],["Changed whenever inconvenient","Standards lose meaning if pressure automatically cancels them."]]),
q("q3","Which is the best example of a leadership code rule?","Tell the truth early, especially when it is uncomfortable","This is observable, actionable, and relevant under pressure.",[["Be a great leader","This is too broad to guide a specific decision."],["Never have conflict","Conflict cannot be fully avoided and can be handled well."],["Make everyone happy","Other people's reactions cannot be controlled."]]),
q("q4","Leadership codes should be reviewed because:","Experience can reveal where standards need clarification","Review improves precision without abandoning core values.",[["Values have no meaning","Review strengthens application; it does not erase meaning."],["Pressure should always lower standards","Pressure is when standards matter most."],["Leaders should change identity constantly","The goal is refinement, not instability."]])]}],challenge:{title:"Use Your Leadership Code Under Pressure",description:"Use your leadership code during one difficult conversation or decision this week and record what changed because you used it.",fields:[{id:"situation",label:"The situation where I will use my code"},{id:"standard",label:"The standard I will apply"},{id:"evidence",label:"What evidence will show I led differently"}],pledge:"I commit to using my leadership standards when pressure makes them hardest to follow."}
},
{
slug:"module-8",number:8,title:"Momentum with Intention",description:"Build a personal operating system and a long-term plan for continued forward movement.",lessons:[
{number:1,title:"Measure Evidence, Not Emotion",videoTitle:"Measure Progress by Evidence",intro:"Feelings matter, but they are poor scoreboards. Progress is easier to see when you track behaviors, outcomes, and completed commitments.",quote:"Your mood can argue with progress. Evidence settles the conversation.",sectionTitle:"Build an evidence scoreboard",sectionBody:"Choose a few indicators that show whether you are living forward: commitments kept, money saved, applications sent, workouts completed, conversations handled, or weekly reviews performed.",activityTitle:"Evidence Scoreboard",fields:[{id:"goal",label:"A goal I want to measure"},{id:"measure1",label:"Evidence measure 1"},{id:"measure2",label:"Evidence measure 2"},{id:"review",label:"How often I will review the evidence"}],quiz:[
q("q1","Why measure evidence instead of emotion alone?","Feelings can change faster than actual progress","Behavioral evidence gives a more stable view of what has been completed.",[["Emotions never matter","Emotions provide useful information; they just should not be the only metric."],["Evidence guarantees success","Evidence improves measurement, not certainty."],["Progress should feel good every day","Real progress can include frustration or fatigue."]]),
q("q2","A useful progress measure is:","Observable and repeatable","You should be able to tell clearly whether the action or result occurred.",[["Completely subjective","Subjective measures are harder to compare over time."],["Based on someone else's life","Metrics should match your goals."],["Changed every day","Constant changes make trends difficult to see."]]),
q("q3","Which is evidence of momentum?","Four scheduled weekly reviews completed","This is a concrete, trackable behavior connected to the system.",[["Feeling more successful","A feeling may be real but is less specific as a progress measure."],["Thinking about a plan","Planning matters, but completed reviews are stronger behavioral evidence."],["Hoping next month is better","Hope is valuable but is not evidence of execution."]]),
q("q4","When emotion says you are failing but evidence shows consistency, you should:","Use the evidence to correct the story","Objective completion can challenge distorted self-assessment.",[["Ignore all emotion forever","The emotion can still be explored without becoming the scoreboard."],["Stop tracking","Removing evidence makes the story harder to test."],["Raise every goal immediately","Consistency should be understood before automatically increasing difficulty."]])]},
{number:2,title:"Build a 90-Day Forward Plan",videoTitle:"Designing Your Next 90 Days",intro:"Ninety days is long enough to create meaningful evidence and short enough to stay concrete. A good plan limits priorities and defines weekly actions.",quote:"A clear quarter beats a vague year.",sectionTitle:"Choose fewer priorities",sectionBody:"Select up to three outcomes, define weekly actions for each, identify obstacles, and schedule review points. The plan should fit your actual capacity.",activityTitle:"90-Day Plan",fields:[{id:"outcome1",label:"90-day outcome 1"},{id:"outcome2",label:"90-day outcome 2"},{id:"outcome3",label:"90-day outcome 3"},{id:"weekly",label:"Weekly actions that support these outcomes"},{id:"reviews",label:"Dates or cadence for weekly reviews"}],quiz:[
q("q1","Why can a 90-day plan be effective?","It balances meaningful time with concrete focus","A quarter is long enough for progress but short enough for specific weekly execution.",[["It guarantees every goal","No timeframe guarantees outcomes."],["It removes the need for weekly action","Weekly behavior is what drives the plan."],["It should include every life goal","Too many priorities dilute focus."]]),
q("q2","A strong 90-day plan should prioritize:","A small number of important outcomes","Limiting priorities protects attention and execution.",[["As many goals as possible","Too many goals create competition for time and energy."],["Only easy wins","Meaningful outcomes may require stretch."],["Only long-term dreams","The plan should translate direction into quarter-sized outcomes."]]),
q("q3","Weekly actions are important because they:","Connect long-term outcomes to repeatable behavior","They turn a 90-day intention into this week's work.",[["Replace the outcomes","Actions support outcomes; both are useful."],["Make reviews unnecessary","Reviews help adjust the actions."],["Guarantee motivation","Actions should be executable without relying on motivation."]]),
q("q4","If a 90-day outcome is off track, the best response is to:","Review evidence and adjust actions or scope","A review helps determine whether the strategy, capacity, or target needs adjustment.",[["Hide the data","Avoiding evidence prevents learning."],["Quit all goals","One miss does not require abandoning the entire plan."],["Add more outcomes","More goals usually add pressure rather than solve the cause."]])]},
{number:3,title:"Create a Return Plan",videoTitle:"Never Go Back",intro:"Setbacks are part of long-term change. A return plan decides what you will do when you drift so one bad day does not become a lost season.",quote:"The goal is not never drifting. The goal is knowing how to return quickly.",sectionTitle:"Plan the recovery before the setback",sectionBody:"Identify early warning signs, minimum standards, people you will contact, and the first action that restarts momentum. Make returning easier than disappearing.",activityTitle:"Return Plan",fields:[{id:"warning",label:"My early warning signs"},{id:"minimum",label:"The minimum standard I will protect"},{id:"support",label:"Who I will contact when I start drifting"},{id:"restart",label:"My first return action"}],quiz:[
q("q1","A return plan exists to:","Shorten the time between drift and recommitment","The plan gives you a rehearsed path back instead of relying on shame or improvisation.",[["Guarantee no setbacks","No plan can eliminate every setback."],["Punish mistakes quickly","Punishment does not necessarily restore useful behavior."],["Hide setbacks from others","Support and honesty can help recovery."]]),
q("q2","Early warning signs are useful because they:","Let you respond before drift becomes larger","Recognizing patterns early makes the return action smaller and faster.",[["Prove failure is inevitable","Warning signs are opportunities for intervention."],["Should be ignored until serious","Waiting allows the pattern to strengthen."],["Only apply to major crises","Small changes in routine can be meaningful signals."]]),
q("q3","A minimum standard during a setback helps:","Protect continuity","A smaller action can keep identity and momentum from collapsing completely.",[["Maintain maximum performance","A minimum is intentionally below the ideal."],["Avoid responsibility","It is a responsible strategy for reduced capacity."],["Eliminate the need for recovery","Recovery may still be necessary."]]),
q("q4","The strongest return action is usually:","Specific and immediately doable","A small first move lowers friction and restarts the system.",[["A complete life overhaul","A huge reset can create more resistance."],["Waiting until Monday","Delaying can extend the drift unnecessarily."],["Making a promise with no action","Behavior is what restarts momentum."]])]}],challenge:{title:"Launch Your 90-Day Forward Plan",description:"Complete your 90-day plan, schedule the first four weekly reviews, and share the plan with one trustworthy person.",fields:[{id:"start",label:"My 90-day start date"},{id:"reviews",label:"My first four weekly review dates/times"},{id:"person",label:"The trustworthy person I will share the plan with"},{id:"return",label:"The first action in my return plan"}],pledge:"I commit to measuring evidence, reviewing weekly, and returning quickly when I drift."}
}
];

export const getModuleContent=(slug:string)=>moduleContent.find(module=>module.slug===slug);
