import type { CourseModuleContent, QuizQuestion } from "./course-content";

const q=(id:string,prompt:string,correct:string,correctWhy:string,wrong:[string,string][]):QuizQuestion=>({id,prompt,correct,options:[{text:wrong[0][0],feedback:wrong[0][1]},{text:correct,feedback:correctWhy},{text:wrong[1][0],feedback:wrong[1][1]},{text:wrong[2][0],feedback:wrong[2][1]}]});

export const moduleOneContent:CourseModuleContent={
slug:"module-1",number:1,title:"The Decision to Turn Forward",description:"Identity, responsibility, fear, and the structure required to create momentum.",
lessons:[
{number:1,title:"You Are Not Starting Over",videoTitle:"The Decision",intro:"Most people think they need a fresh start. But you do not need a reset—you need a decision. You are not blank, erased, or without history. You are experienced, shaped, and capable of using what you have learned.",quote:"Turning forward is not denial. It is integration.",sectionTitle:"Identity, reputation, and responsibility",sectionBody:"Reputation is what people think. Identity is what you decide. Rebuild identity first; reputation follows consistent action. Responsibility says, ‘That was me, that decision was mine, and now I move.’ Own your choices without destroying your worth.",activityTitle:"Identity Rewrite",fields:[{id:"waiting",label:"I am no longer waiting for…"},{id:"becoming",label:"Write at least five sentences beginning with ‘I am becoming…’",min:20}],quiz:[
q("q1","Turning forward means:","Integrating experience and moving deliberately","Exactly. You use what you have learned and make intentional choices about who you are becoming.",[["Erasing your history","Your history cannot be erased. Turning forward means learning from it without allowing it to control your next decision."],["Waiting until your past no longer matters","Growth does not require waiting for the past to disappear."],["Proving everyone else wrong","Turning forward is an internal decision, not a performance built around other people's opinions."]]),
q("q2","What is the healthiest relationship with your past?","Own it, learn from it, and keep moving","Correct. Responsibility and growth can exist together without shame.",[["Pretend it never happened","Denial prevents integration and accountability."],["Let it permanently define you","Your past is part of your story, but it does not have to become your permanent identity."],["Only discuss the parts that make you look strong","Selective ownership avoids accountability."]]),
q("q3","What should be rebuilt first?","Identity","Correct. Decide who you are becoming, then let consistent action shape your reputation over time.",[["Reputation","Reputation is what others think and usually changes after they observe consistent behavior."],["Other people's approval","Approval is outside your control and is not a stable foundation for transformation."],["Your public image","A polished image without an internal identity change does not create durable transformation."]]),
q("q4","Responsibility without shame is:","Ownership without self-destruction","Correct. You can own what happened, learn from it, and still believe you are capable of growth.",[["Avoiding accountability","Responsibility requires acknowledging your choices rather than avoiding them."],["Punishing yourself indefinitely","Permanent self-punishment is shame, not productive accountability."],["Blaming circumstances for every decision","Circumstances matter, but responsibility includes owning the choices that were yours."]])]},
{number:2,title:"Fear Is Information, Not Instruction",videoTitle:"Moving While Afraid",intro:"Fear often appears the moment you attempt to grow. It may tell you something is unfamiliar, important, or stretching you—but fear does not get to vote.",quote:"Fear is information. Avoidance is the real enemy.",sectionTitle:"Survival mode versus strategy mode",sectionBody:"Survival mode reacts. Strategy mode pauses, evaluates, plans, and moves deliberately. The goal is not to stop feeling fear; it is to stop allowing fear to make every decision.",activityTitle:"Fear Mapping Tool",fields:[{id:"fear",label:"Current fear"},{id:"think",label:"What I think will happen"},{id:"worst",label:"Worst-case scenario"},{id:"likely",label:"Most likely scenario"},{id:"action",label:"One forward action I can take this week"}],quiz:[
q("q1","Fear is best understood as:","A signal to evaluate","Correct. Fear provides information that you can examine before choosing a deliberate response.",[["A command to stop","Fear can alert you, but it does not automatically determine what you should do next."],["Proof that you are failing","Fear often appears during growth and unfamiliar situations."],["A reason to avoid uncertainty","Avoidance can prevent growth and reinforce fear."]]),
q("q2","Survival mode is primarily:","Reactive","Correct. Survival mode responds quickly to perceived threats rather than pausing for deliberate strategy.",[["Strategic","Strategy mode pauses, evaluates, plans, and then acts."],["Long-range and deliberate","Long-range thinking is characteristic of strategy mode."],["Focused on measured experimentation","Measured experimentation involves deliberate learning rather than automatic survival reactions."]]),
q("q3","Scarcity thinking can affect:","Both confidence and decisions","Correct. Scarcity can narrow what you believe is possible and influence the actions you take.",[["Only confidence","Scarcity can shape feelings and choices."],["Only finances","Its influence is broader than finances."],["Only relationships","It can influence confidence, risk, work, money, and relationships."]]),
q("q4","What is the goal when fear appears?","Pause, evaluate, and choose a forward action","Correct. Strategy mode uses fear as information and then chooses an intentional response.",[["Never feel fear again","The goal is changing how you respond to fear, not eliminating it."],["Let fear make the safest decision","Fear is information, not the decision-maker."],["Wait until you feel completely confident","Confidence often follows action."]])]},
{number:3,title:"The First Discipline: Structure",videoTitle:"Systems Create Stability",intro:"Motivation is unreliable. Discipline builds momentum. Freedom without structure can feel unstable, but structure creates safety, safety creates clarity, and clarity makes progress possible.",quote:"You cannot out-motivate chaos. You must out-structure it.",sectionTitle:"Micro-commitments",sectionBody:"Choose small, repeatable behaviors: a wake time, a study block, a savings percentage, ten pages of reading, or a scheduled workout. Momentum is built in inches.",activityTitle:"Structure Builder",fields:[{id:"wake",label:"My wake time"},{id:"nonnegotiables",label:"My three non-negotiables"},{id:"growth",label:"My growth block: time and activity"},{id:"eliminate",label:"One habit I am eliminating"}],quiz:[
q("q1","Why is structure more dependable than motivation?","Repeatable systems do not depend on how you feel that day","Correct. A system gives you a predetermined action even when motivation rises or falls.",[["Structure removes every difficult emotion","Structure can support you during difficult emotions, but it does not eliminate them."],["Motivation is always harmful","Motivation can be useful; the problem is relying on it as your only system."],["Structure guarantees immediate results","Meaningful results still require time and repeated action."]]),
q("q2","What is a micro-commitment?","A small repeatable behavior you can consistently perform","Correct. Micro-commitments make progress specific, manageable, and repeatable.",[["A major life overhaul completed in one day","The lesson emphasizes sustainable small actions."],["A goal you keep private so no one can challenge it","Privacy does not define a micro-commitment."],["An action you only take when inspired","That makes the behavior dependent on motivation."]]),
q("q3","According to the lesson, structure creates:","Safety and clarity that support progress","Correct. Predictable structure can create stability, which makes deliberate progress easier.",[["A life with no uncertainty","No system removes all uncertainty."],["Permanent motivation","Structure reduces your dependence on motivation."],["Permission to avoid difficult decisions","Good structure supports responsible action."]]),
q("q4","Which is the strongest example of a useful system?","Schedule a 30-minute growth block at 7:00 p.m. each weekday","Correct. It defines the behavior, duration, and schedule, making execution easier to repeat.",[["Work out whenever you happen to feel energized","This still depends on mood."],["Read more someday","The intention is too vague to function as a system."],["Wait for a perfect week before beginning","Waiting for ideal conditions delays practice."]])]}],
challenge:{title:"Turn the Decision into Action",description:"Choose one behavior in each category. Keep it realistic, measurable, and specific enough to complete within seven days.",fields:[{id:"routine",label:"One structured daily routine"},{id:"fearAction",label:"One fear-facing action"},{id:"identityBehavior",label:"One identity-building behavior"}],pledge:"I commit to completing these actions during the next seven days."}
};
