"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Header from "@/components/Header";
import { SECURITY_QUESTIONS } from "@/lib/security-questions";

export default function Register() {
 const router=useRouter(); const [paid,setPaid]=useState(false); const [ready,setReady]=useState(false);
 const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const [securityQuestion1,setSecurityQuestion1]=useState(""); const [securityAnswer1,setSecurityAnswer1]=useState("");
 const [securityQuestion2,setSecurityQuestion2]=useState(""); const [securityAnswer2,setSecurityAnswer2]=useState("");
 const [securityQuestion3,setSecurityQuestion3]=useState(""); const [securityAnswer3,setSecurityAnswer3]=useState("");
 useEffect(()=>{setPaid(new URLSearchParams(window.location.search).get("paid")==="1");setReady(true)},[]);
 async function submit(e:FormEvent){e.preventDefault(); setBusy(true); setMessage(""); const securityAnswers=[{question:securityQuestion1,answer:securityAnswer1},{question:securityQuestion2,answer:securityAnswer2},{question:securityQuestion3,answer:securityAnswer3}]; const res=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:name,email,password,securityAnswers})}); const data=await res.json(); setBusy(false); if(!res.ok){setMessage(data.error||"Unable to create account.");return;} setMessage("Account created. You can now use User Login."); setTimeout(()=>router.push("/login"),900);}
 const questionOptions=(selected:string)=><><option value="">Select a security question</option>{SECURITY_QUESTIONS.map(q=><option key={q.id} value={q.id} disabled={[securityQuestion1,securityQuestion2,securityQuestion3].includes(q.id)&&selected!==q.id}>{q.label}</option>)}</>;
 if(!ready) return <main><Header/><section className="auth-shell"><div className="auth-card"><h1>Checking enrollment…</h1></div></section></main>;
 if(!paid) return <main><Header/><section className="auth-shell"><div className="auth-card"><span className="eyebrow">PAID ACCESS</span><h1>Purchase required</h1><p>User accounts are available after purchasing Turning Forward. Preview the full course outline before enrolling.</p><Link className="button full" href="/course/turning-forward">Preview course & enroll — $97</Link><small>Already purchased and created your account? <Link href="/login">User Login</Link></small></div></section></main>;
 return <main><Header/><section className="auth-shell"><form className="auth-card" onSubmit={submit}><span className="eyebrow">PAYMENT RECEIVED</span><h1>Create your user account</h1><p>Use the same email address you used for your $97 Turning Forward purchase. Your email will be your login username.</p>{message&&<div className="notice">{message}</div>}<label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Purchase email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="notice"><strong>Account recovery questions</strong><br/>Choose three different questions. Your answers are stored securely and are not displayed back to you.</div><label>Security question 1<select required value={securityQuestion1} onChange={e=>setSecurityQuestion1(e.target.value)}>{questionOptions(securityQuestion1)}</select></label><label>Answer 1<input type="password" minLength={2} required autoComplete="off" value={securityAnswer1} onChange={e=>setSecurityAnswer1(e.target.value)}/></label><label>Security question 2<select required value={securityQuestion2} onChange={e=>setSecurityQuestion2(e.target.value)}>{questionOptions(securityQuestion2)}</select></label><label>Answer 2<input type="password" minLength={2} required autoComplete="off" value={securityAnswer2} onChange={e=>setSecurityAnswer2(e.target.value)}/></label><label>Security question 3<select required value={securityQuestion3} onChange={e=>setSecurityQuestion3(e.target.value)}>{questionOptions(securityQuestion3)}</select></label><label>Answer 3<input type="password" minLength={2} required autoComplete="off" value={securityAnswer3} onChange={e=>setSecurityAnswer3(e.target.value)}/></label><button className="button full" disabled={busy}>{busy?"Creating account…":"Create user account"}</button><small>Already registered? <Link href="/login">User Login</Link></small></form></section></main>;
}
