import type { ContentBlock, CourseDefinition, CourseModule, QuestionDefinition } from "./types";

type ModuleSeed = {
  title: string;
  coreQuestion: string;
  keyIdea: string;
  definition: string;
  recognizeReflection: string;
  realLifePrompt: string;
  replacementPrompt: string;
  activityTitle: string;
  activityInstructions: string;
  activityFields: string[];
  scenario?: string;
  scenarioPrompt?: string;
};

const question = (id: string, prompt: string, correctLabel: string, wrongLabels: string[]): QuestionDefinition => ({
  id,
  prompt,
  options: [
    { id: "a", label: correctLabel, correct: true, feedback: "Correct. This response names the thinking pattern and moves toward responsibility." },
    ...wrongLabels.map((label, index) => ({ id: String.fromCharCode(98 + index), label, feedback: "Not quite. Look for the response that examines the thought instead of defending, avoiding, or escalating it." })),
  ],
});

function buildModule(seed: ModuleSeed, index: number): CourseModule {
  const number = index + 1;
  const base = `m${number}`;
  const realLifeBlock: ContentBlock = seed.scenario
    ? { type: "decision-point", id: `${base}-decision`, scenario: seed.scenario, prompt: seed.scenarioPrompt || seed.realLifePrompt }
    : { type: "catch-the-thought", id: `${base}-catch`, prompt: seed.realLifePrompt, statements: ["I do not need to look at my part in this.", "The immediate reaction matters more than the long-term result.", "If I slow down, I can identify the thought before I act on it."] };

  return {
    slug: `module-${number}`,
    number,
    title: seed.title,
    coreQuestion: seed.coreQuestion,
    keyIdea: seed.keyIdea,
    description: seed.definition,
    lessons: [
      { slug: "lesson-1", number: 1, title: "Recognize It", objective: `Recognize ${seed.title.toLowerCase()} in thoughts, reactions, and choices.`, blocks: [
        { type: "key-idea", text: seed.keyIdea },
        { type: "paragraph", text: seed.definition },
        { type: "reflection", id: `${base}-l1-reflection`, prompt: seed.recognizeReflection, minChars: 50 },
        { type: "knowledge-check", question: question(`${base}-l1-check`, `What is the strongest first step when ${seed.title.toLowerCase()} shows up?`, "Name the thought pattern before defending or acting on it.", ["Act quickly so the feeling passes.", "Focus only on what other people did.", "Ignore the thought unless there is a consequence."]) },
      ]},
      { slug: "lesson-2", number: 2, title: "Catch It in Real Life", objective: "Slow down a real-life situation and identify the thought, choice point, and likely consequence.", blocks: [
        realLifeBlock,
        { type: "reflection", id: `${base}-l2-reflection`, prompt: seed.realLifePrompt, minChars: 50 },
        { type: "knowledge-check", question: question(`${base}-l2-check`, "What makes a decision point useful?", "It creates a pause where you can examine the thought before choosing an action.", ["It proves the other person was wrong.", "It removes every uncomfortable feeling.", "It guarantees there will be no consequence."]) },
      ]},
      { slug: "lesson-3", number: 3, title: "Correct the Thought", objective: "Replace the old thinking pattern with a responsible thought and a concrete next action.", blocks: [
        { type: "workbook-activity", id: `${base}-activity`, title: seed.activityTitle, instructions: seed.activityInstructions, fields: seed.activityFields },
        { type: "reflection", id: `${base}-l3-reflection`, prompt: seed.replacementPrompt, minChars: 50 },
        { type: "knowledge-check", question: question(`${base}-l3-check`, "What does correcting a thinking error require?", "A different thought followed by a different practiced response.", ["A promise that you will never feel the thought again.", "A reason why the old response made sense.", "Waiting until someone else changes first."]) },
      ]},
    ],
  };
}

const seeds: ModuleSeed[] = [
  { title: "The Closed Channel", coreQuestion: "What truth am I refusing to hear?", keyIdea: "A closed channel means you block out feedback, criticism, and truth. When you're not listening, you're not learning.", definition: "The Closed Channel is a mental and emotional shutdown used to avoid feedback, change, or accountability. It shows up as refusing to listen, reflect, or learn from others.", recognizeReflection: "When has someone tried to help or correct you and you shut down, argued, ignored them, or decided they did not understand you? What happened next?", realLifePrompt: "In the situation, what thought closes the channel, and what would listening without immediately agreeing or defending yourself make possible?", replacementPrompt: "Write the response you can use the next time feedback makes you defensive. Show how you will listen, pause, and decide what is useful before reacting.", activityTitle: "Feedback Response Reset", activityInstructions: "Use the workbook pattern: identify what was said, how you responded, and what a more open response could sound like now.", activityFields: ["What was said?", "How did I respond?", "What is my new response?"], scenario: "Lisa was assigned a counselor during her transition program. The counselor tried to talk with her about goals, past trauma, and communication skills. Lisa answered with sarcasm or silence, rolled her eyes at feedback, and said, “You don’t know me.” When asked whether she wanted things to change, Lisa said she was only there so she would not get written up.", scenarioPrompt: "Where did Lisa close the channel, and what could she have done differently without pretending she agreed with everything the counselor said?" },
  { title: "Viewing Self as a Good Person", coreQuestion: "Am I using good deeds to avoid looking at harm?", keyIdea: "Doing a few good things does not erase harm. True change means owning your full story—not just the parts that make you look good.", definition: "This thinking error uses isolated good deeds to justify, minimize, or distract from harmful choices and patterns.", recognizeReflection: "What good things have you pointed to when you did not want to look directly at a harmful choice, broken commitment, or person you hurt?", realLifePrompt: "Catch the moment when a true statement about something good becomes a shield against accountability for something harmful.", replacementPrompt: "How can you hold both truths at once: that you have done good things and that you are still responsible for harm you caused?", activityTitle: "The Mirror Doesn't Lie — Life Balance Sheet", activityInstructions: "List good deeds and harmful actions side by side. Do not use one column to cancel the other; use both to see yourself more clearly.", activityFields: ["Good deeds I can acknowledge", "Harmful actions I must also own", "What seeing both clearly changes for me"] },
  { title: "Victimstance", coreQuestion: "Where am I giving away responsibility?", keyIdea: "Blaming others helps you avoid responsibility, but it also stops you from growing.", definition: "Victimstance means seeing yourself as the constant victim in a way that allows you to avoid examining your own choices or responsibility.", recognizeReflection: "Who, what system, what relationship, or what part of your upbringing do you blame most often? What part of the story belongs to your choices?", realLifePrompt: "Separate what was unfair or outside your control from the next decision that still belonged to you.", replacementPrompt: "Rewrite one blame-based story with you as the person responsible for the next choice, without denying what happened to you.", activityTitle: "Flip the Story", activityInstructions: "Use the workbook format to rewrite a situation you blamed on someone else. Keep the facts, then change the part where you give away your power to choose.", activityFields: ["What had happened was…", "What was outside my control", "My new narrative: what choice belonged to me?"], scenario: "James had been released for two months and had not found stable employment. When his parole officer reminded him he was behind on supervision fees, he exploded and blamed the system. He did not hear her offer to help him find a job because he was too focused on the unfairness he felt.", scenarioPrompt: "What part of James's frustration may be understandable, and where does victimstance keep him from hearing an option that could help him move forward?" },
  { title: "Lack of Effort", coreQuestion: "Where am I expecting results without sustained work?", keyIdea: "Growth takes work. Avoiding effort is a choice that holds you back.", definition: "Lack of Effort is choosing procrastination, quitting, minimal effort, or avoidance as a repeated pattern instead of consistently doing the work a goal requires.", recognizeReflection: "What tasks do you avoid, delay, or abandon most often? What do you usually tell yourself right before you stop putting in effort?", realLifePrompt: "Identify the thought that turns discomfort, boredom, or slow progress into a reason to quit.", replacementPrompt: "What is one small action you can repeat even when motivation is low, and how will you know you completed it?", activityTitle: "S.T.E.P.S. — Strategic Tasks Executed Persistently and Slowly", activityInstructions: "Break one larger goal into small actions that can be completed consistently. Progress is the target, not perfection.", activityFields: ["Goal", "Small step 1", "Small step 2", "Small step 3", "When I will complete these steps"] },
  { title: "Lack of Interest in Responsible Performance", coreQuestion: "What responsibilities am I refusing to fully own?", keyIdea: "Responsible roles—like parent, worker, partner, or student—build stability and self-respect. Avoiding them produces instability.", definition: "This thinking error dismisses, resents, or avoids roles that require dependable, responsible performance.", recognizeReflection: "Which role in your life have you treated like it should only matter when it is convenient? What has that cost you or other people?", realLifePrompt: "Notice the thought that makes a responsibility sound optional even when other people depend on your performance.", replacementPrompt: "Choose one role and describe what responsible performance would look like in ordinary daily behavior, not just good intentions.", activityTitle: "Responsibility Role Inventory", activityInstructions: "List the roles you play, rate your current performance from 1 to 5, and choose one role to improve through specific behavior.", activityFields: ["Role", "My rating (1–5)", "What responsible performance looks like", "One behavior I will improve this week"] },
  { title: "Ownership Attitude", coreQuestion: "Where am I confusing control with respect?", keyIdea: "You do not own people. Controlling others damages relationships and keeps you isolated.", definition: "Ownership Attitude treats people, access, attention, or relationships as possessions and uses control instead of mutual respect.", recognizeReflection: "When have you acted as if another person owed you access, agreement, loyalty, attention, or obedience? What were you afraid would happen if you let go of control?", realLifePrompt: "Catch the thought that turns a relationship into a possession or turns disagreement into disrespect.", replacementPrompt: "Write a respect-based alternative that allows the other person choice, boundaries, and dignity even when you do not get what you want.", activityTitle: "Not Mine Exercise", activityInstructions: "Name controlling behaviors, their results, and a new approach based on respect rather than ownership.", activityFields: ["Controlling behavior", "Result", "New respectful approach"] },
  { title: "Fear of Fear", coreQuestion: "What fear is hiding underneath my reaction?", keyIdea: "Denying fear does not make it disappear. Naming fear gives you more power over how you respond to it.", definition: "Fear of Fear means denying, avoiding, or disguising fear—often behind anger, aggression, excuses, or withdrawal—rather than acknowledging it and choosing a response.", recognizeReflection: "What fear have you hidden behind anger, aggression, indifference, or an excuse? What did the disguise protect you from admitting?", realLifePrompt: "Identify the fear underneath the reaction, then separate feeling afraid from choosing what to do next.", replacementPrompt: "Name one fear directly and write one action you can take while the fear is still present.", activityTitle: "Fear Board", activityInstructions: "Identify your top fears and pair each one with a direct action that faces rather than avoids it.", activityFields: ["Fear 1 + action", "Fear 2 + action", "Fear 3 + action"], scenario: "Kevin was invited to a job interview but canceled at the last minute. He told people the job was not his kind of thing and was not worth his time. In truth, Kevin was afraid of rejection and failure, so he avoided the interview.", scenarioPrompt: "What fear is Kevin disguising, what story does he use to avoid naming it, and what would facing the fear look like?" },
  { title: "Lack of Time Perspective", coreQuestion: "What will this decision cost me later?", keyIdea: "If you only think short-term, you keep making the same mistakes. Growth means looking ahead.", definition: "Lack of Time Perspective means focusing on the immediate feeling, reward, pressure, or relief without seriously considering the longer-term consequences.", recognizeReflection: "What short-term decision brought long-term damage in your life? What future cost did you ignore, minimize, or assume you would deal with later?", realLifePrompt: "Catch the thought that says only right now matters and compare the immediate payoff with the likely future cost.", replacementPrompt: "Write a future-focused question you can ask yourself before a high-risk decision and apply it to one current choice.", activityTitle: "Future Letter", activityInstructions: "Set a 1-month, 6-month, and 1-year goal and identify actions that protect the future you say you want.", activityFields: ["1-month goal + two steps", "6-month goal + two steps", "1-year goal + two steps"] },
  { title: "Power Thrust", coreQuestion: "Am I trying to control others instead of myself?", keyIdea: "Trying to control others through fear, manipulation, or dominance weakens the power that matters most: self-control.", definition: "Power Thrust uses intimidation, manipulation, dominance, force, or being the loudest person in the room to control people or situations.", recognizeReflection: "When have you used intimidation, volume, threats, manipulation, or pressure because you needed to feel in control or respected? What did you gain and what did you lose?", realLifePrompt: "Identify the moment where influence turns into domination and where self-control would create a stronger result.", replacementPrompt: "Define positive power in your own words and describe how you can lead, disagree, or set a boundary without intimidation.", activityTitle: "Power Redefined", activityInstructions: "Identify relationships where force or dominance damaged trust and list specific ways to rebuild trust through consistent behavior.", activityFields: ["Relationship 1 + way to rebuild", "Relationship 2 + way to rebuild", "Relationship 3 + way to rebuild"], scenario: "During group sessions, Malik talks over others and dominates the conversation. He believes that if he is not the loudest or most opinionated, people will not take him seriously. When another member challenges him respectfully, Malik reads it as disrespect and shuts down.", scenarioPrompt: "Where does Malik confuse volume or control with power, and what would self-controlled leadership look like in the same group?" },
  { title: "Uniqueness", coreQuestion: "Where do I believe the rules should not apply to me?", keyIdea: "Thinking the rules do not apply to you creates excuses and isolation. You are not alone, and you are not exempt from consequences.", definition: "Uniqueness is the belief that your circumstances, intelligence, pain, goals, or identity make you an exception to rules, expectations, or consequences that apply to other people.", recognizeReflection: "What rule, expectation, boundary, or consequence have you treated as if it should not apply to you? What story made you feel like the exception?", realLifePrompt: "Catch the sentence that begins with some version of 'but my situation is different' and test whether it is describing a real difference or creating an exemption.", replacementPrompt: "How could seeing yourself as connected to other people—and subject to the same basic expectations—change your next decision?", activityTitle: "Common Ground Circles", activityInstructions: "Write about times you thought you were the exception and compare that belief with the real outcome.", activityFields: ["The time I thought I was an exception", "What I believed made me different", "What really came out of it", "What I see now"] },
];

export const thoughtToFreedomCourse: CourseDefinition = {
  slug: "thought-to-freedom",
  title: "Thought to Freedom",
  subtitle: "Correcting Criminal Thinking Errors",
  supportingLine: "Examine the thought. Challenge the pattern. Choose a different response.",
  description: "An interactive TCF Learn course for identifying recurring criminal thinking errors, connecting thought patterns to choices and consequences, and practicing responsible replacement thinking.",
  orientation: { slug: "orientation", number: 0, title: "Before the Action Comes the Thought", objective: "Understand how thoughts influence choices, actions, and consequences and learn the five-step correction loop used throughout the course.", blocks: [
    { type: "key-idea", text: "The goal is not to label a person forever. The goal is to examine a thinking pattern early enough to make a different choice." },
    { type: "paragraph", text: "Throughout this course, use the chain Thought → Choice → Action → Consequence. The earlier you identify the thought, the more room you create to choose a different response." },
    { type: "paragraph", text: "The course practice is: Recognize → Examine → Interrupt → Replace → Practice. Antoine Rivers developed this course from lessons he studied and applied while incarcerated, including his study of criminal-thinking work by Dr. Stanton Samenow and Dr. Samuel Yochelson. The course presents those lessons through Antoine's own lived-experience and TCF Learn framework; it does not claim endorsement by those scholars." },
    { type: "reflection", id: "orientation-reflection", prompt: "Think of one decision you wish you could revisit. Without excusing or condemning yourself, what thought came before the choice and action?", minChars: 50 },
    { type: "knowledge-check", question: question("orientation-check", "Where does this course ask you to intervene first?", "At the thought and choice point, before the action becomes automatic.", ["Only after a consequence happens.", "Only when another person confronts you.", "Only when the feeling disappears."]) },
  ]},
  modules: seeds.map(buildModule),
};

export const thoughtToFreedomActionPlanFields = ["My three strongest recurring thinking errors", "My warning signs", "My common triggers", "What I usually tell myself", "What I will tell myself instead", "One behavior I will practice for each pattern", "My accountability person or support resource", "My 30-day practice plan"] as const;
